# Marian configuration file generated at 2024-04-28 07:14:29 +0000 with version v1.12.0 65bf82ff 2023-02-21 09:56:29 -0800
# General options

workspace: 8192
valid-log: valid.log

devices:
  - 0
  - 1
num-devices: 2

# Model options
model: model.npz
pretrained-model: ""
ignore-model-config: false
no-reload: false
type: transformer
seed: 0

train-sets:
  - train.sp.en
  - train.sp.es

guided-alignment: train.sp.en.es.align

valid-sets:
  - val.sp.en
  - val.sp.es
  
valid-freq: 10000u
valid-metrics:
  - cross-entropy
  - bleu-detok

data-weighting: ""
data-weighting-type: sentence
max-length: 100
mini-batch-fit: false

vocabs:
  - vocab-en.yml
  - vocab-es.yml

dim-vocabs:
  - 32000
  - 32000

keep-best: true
overwrite: true
early-stopping: 10
early-stopping-on: all

transformer-dropout: 0.2
transformer-dropout-attention: 0
transformer-dropout-ffn: 0


authors: false
cite: false
build-info: ""

log: ""
log-level: info
log-time-zone: ""
quiet: false
quiet-translation: false

check-nan: false
interpolate-env-vars: false
relative-paths: false
sigterm: save-and-exit



dim-emb: 512
factors-dim-emb: 0
factors-combine: sum
lemma-dependency: ""
lemma-dim-emb: 0
dim-rnn: 1024
enc-type: bidirectional
enc-cell: gru
enc-cell-depth: 1
enc-depth: 1
dec-cell: gru
dec-cell-base-depth: 2
dec-cell-high-depth: 1
dec-depth: 1
skip: false
layer-normalization: false
right-left: false
input-types:
  []
best-deep: false
tied-embeddings: false
tied-embeddings-src: false
tied-embeddings-all: false
output-omit-bias: false
transformer-heads: 8
transformer-no-projection: false
transformer-rnn-projection: false
transformer-pool: false
transformer-dim-ffn: 2048
transformer-decoder-dim-ffn: 0
transformer-ffn-depth: 2
transformer-decoder-ffn-depth: 0
transformer-ffn-activation: swish
transformer-dim-aan: 2048
transformer-aan-depth: 2
transformer-aan-activation: swish
transformer-aan-nogate: false
transformer-decoder-autoreg: self-attention
transformer-tied-layers:
  []
transformer-guided-alignment-layer: last
transformer-preprocess: ""
transformer-postprocess-emb: d
transformer-postprocess: dan
transformer-postprocess-top: ""
transformer-train-position-embeddings: false
transformer-depth-scaling: false
bert-mask-symbol: "[MASK]"
bert-sep-symbol: "[SEP]"
bert-class-symbol: "[CLS]"
bert-masking-fraction: 0.15
bert-train-type-embeddings: true
bert-type-vocab-size: 2
dropout-rnn: 0
dropout-src: 0
dropout-trg: 0

# Training options
cost-type: ce-sum
multi-loss-type: sum
unlikelihood-loss: false


sentencepiece-alphas:
  []
sentencepiece-options: ""
sentencepiece-max-lines: 2000000
after-epochs: 0
after-batches: 0
after: 0e
disp-freq: 1000u
disp-first: 0
disp-label-counts: true
save-freq: 10000u
logical-epoch:
  - 1e
  - 0

max-length-crop: false
tsv: false
tsv-fields: 0
shuffle: data
no-shuffle: false
no-restore-corpus: false
tempdir: /tmp
sqlite: ""
sqlite-drop: false

no-nccl: false
sharding: global
sync-freq: 200u
cpu-threads: 0
mini-batch: 64
mini-batch-words: 0

mini-batch-fit-step: 10
gradient-checkpointing: false
maxi-batch: 100
maxi-batch-sort: trg
shuffle-in-ram: false
data-threads: 8
all-caps-every: 0
english-title-case-every: 0
mini-batch-words-ref: 0
mini-batch-warmup: 0
mini-batch-track-lr: false
mini-batch-round-up: true
optimizer: adam
optimizer-params:
  []
optimizer-delay: 1
sync-sgd: false
learn-rate: 0.0001
lr-report: false
lr-decay: 0
lr-decay-strategy: epoch+stalled
lr-decay-start:
  - 10
  - 1
lr-decay-freq: 50000
lr-decay-reset-optimizer: false
lr-decay-repeat-warmup: false
lr-decay-inv-sqrt:
  - 0
lr-warmup: 0
lr-warmup-start-rate: 0
lr-warmup-cycle: false
lr-warmup-at-reload: false
label-smoothing: 0
factor-weight: 1
clip-norm: 1
exponential-smoothing: 0
guided-alignment-cost: ce
guided-alignment-weight: 0.1

embedding-vectors:
  []
embedding-normalization: false
embedding-fix-src: false
embedding-fix-trg: false
fp16: false
precision:
  - float32
  - float32
cost-scaling:
  []
gradient-norm-average-window: 100
dynamic-gradient-scaling:
  []
check-gradient-nan: false
normalize-gradient: false
train-embedder-rank:
  []
quantize-bits: 0
quantize-optimization-steps: 0
quantize-log-based: false
quantize-biases: false
ulr: false
ulr-query-vectors: ""
ulr-keys-vectors: ""
ulr-trainable-transformation: false
ulr-dim-emb: 0
ulr-dropout: 0
ulr-softmax-temperature: 1
task:
  - transformer-big
# Validation set options

valid-reset-stalled: false
valid-reset-all: false

beam-size: 12
normalize: 0
max-length-factor: 3
word-penalty: 0
allow-unk: false
n-best: false
word-scores: false
valid-mini-batch: 32
valid-max-length: 1000
valid-script-path: ""
valid-script-args:
  []
valid-translation-output: ""


